### ISSUE TITLE
Vercel Platforms launch to-do list

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#1138]
Note: for readability I'm referring to the vercel platforms work done in the `feature/vercel-platforms` branch as `the feature branch` in all steps below.

We do not have to put the live sites into maintenance mode for this. The static sites should remain as-is, only newly published articles will potentially be affected by the changes, I think.

Then:

* [x] Create a dump of the production database from Hasura: [documented in the wiki](https://github.com/news-catalyst/next-tinynewsdemo/wiki/Platforms-Launch---Database-Info)
  * _**note:**_ tested today, hasura api endpoint works as expected
* [x] How to rollback database changes in production: [same wiki page](https://github.com/news-catalyst/next-tinynewsdemo/wiki/Platforms-Launch---Database-Info)
* **DONE:** Ensure the feature branch incorporates any code changes made in main:
  * [x] Merge latest `main` branch into `feature/vercel-platforms`
  * [x] Resolve conflicts, there will surely be some
  * [x] Build locally without errors
* [ ] Merge feature/vercel-platforms PR! https://github.com/news-catalyst/next-tinynewsdemo/pull/1103
* [ ] Create stable branch: https://github.com/news-catalyst/next-tinynewsdemo/tree/stable
* [x] Update Hasura production instance: [full details documented in the wiki](https://github.com/news-catalyst/next-tinynewsdemo/wiki/Platforms-Launch---Database-Info)
  * [x] apply migrations
  * [x] add settings table content and organizations data for customDomain/subdomain values
  * [x] export metadata from staging Hasura instance - https://github.com/news-catalyst/hasura/pull/111
  * [x] apply metadata to production Hasura instance
* [x] Review authorized/redirect URIs in [Google console OAuth settings](https://console.cloud.google.com/apis/credentials/oauthclient/1027657873629-ks6qtf9qjbd73ic28488mvketcflfmh5.apps.googleusercontent.com?project=webiny-sidebar-publishing) - the production urls were already specified here, all good
* [x] Ensure settings ENV vars in [tiny-news-sites Vercel project](https://vercel.com/news-catalyst/tiny-news-sites/settings/environment-variables) are updated for production (keep `preview` version for staging):
  * NEXT_PUBLIC_ASSETS_DOMAIN
  * HASURA_API_URL
  * HASURA_ADMIN_SECRET
* [x] Review deploy.sh - it should build production VERCEL_ENV in the `stable` branch already, make sure
* [x] Update production branch in [tiny-news-sites Vercel project Git settings](https://vercel.com/news-catalyst/tiny-news-sites/settings/git) from `feature/vercel-platforms` to `stable`
* [x] replace production authorization webhook with new version: [details in wiki](https://github.com/news-catalyst/next-tinynewsdemo/wiki/Platforms-Launch---Webhook-Info)
* [ ] Production sites DNS should be in the tiny-news-sites Vercel project
* [x] Go live / deploy fresh to production
* [x] Test production sites
* [ ] Update sidebar API settings to point to new production API
* [ ] Test sidebar publishing article & page

**Comment by TylerFisher** [comment]
One thing I'll add here: we should make a snapshot the production database and have rollback plans in case anything goes catastrophically wrong.
