### ISSUE TITLE
Front-end QA checklist

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#886]
**TinyCMS**

Check the following admin pages in the main locale, and if the site uses other languages, check those as well:

- [ ] Authors: list, add, update, delete
- [ ] Sections: list, add, update, _specifically show/hide from nav_
- [ ] Tags: list, add, update, delete
- [ ] Settings: 
  - [ ] rich text areas
  - [ ] image uploads can swap images
  - [ ] live previews work with rich text and otherwise
  - [ ] (testing sites: can toggle landing page mode, comments, design & colours)
  - [ ] text input fields are editable, not blank
- [ ] Homepage Editor: 
  - [ ] editor loads/renders
  - [ ] can switch layout
  - [ ] can search for articles
  - [ ] can switch featured articles
  - [ ] can save choices
- [ ] Analytics: each section renders, data looks reasonable

**Public-facing Site**

- [ ] Landing page: renders, allows newsletter signups
- [ ] Static pages:
  - [ ] About (in each locale)
  - [ ] Staff
  - [ ] Donate
  - [ ] Thank You
  - [ ] Any custom static pages published
- [ ] Homepage: 
  - [ ] if not in landing mode, this should render whatever is configured in the Homepage Editor
  - [ ] article stream appears below featured section, includes headlines, section links, authors, dates, images if present
  - [ ] nav renders correctly
  - [ ] signup form works
  - [ ] links to article archives
- [ ] Article archive
  - [ ] lists articles in stream in reverse chron order
  - [ ] is paginated
- [ ] Section index lists the right articles in a stream
- [ ] Author index 
  - [ ] lists the right articles in a stream
  - [ ] includes author name, bio, title, image
- [ ] Article page
  - [ ] includes section link
  - [ ] renders headline, then search description
  - [ ] displays first published at, includes updated date if different
  - [ ] includes byline, links to author page
  - [ ] shareable via facebook and twitter buttons
  - [ ] includes "Read in <other language>" if article is published in multiple locales
  - [ ] renders article contents: regular text, bold, italic, links, lists, and embeds
  - [ ] includes a main image if present
  - [ ] renders additional images, includes alt text, captions
  - [ ] displays author bio below article
  - [ ] displays tag links below article
  - [ ] includes recirculation links if other articles are published in the section/category
- [ ] General
  - [ ] Nav and footer appears on all pages
  - [ ] Footer includes social links, copyright
  - [ ] tk

**Other**

- [ ] Data importers - check github action for status, check hasura for data recency / sanity check
